[Monochromator]
step = 20
start_wave_length = 950
end_wave_length = 1700
raster_1_start = 200
raster_1_end = 400
raster_2_start = 400
raster_2_end = 1000
raster_3_start = 1000
raster_3_end = 2200

[Serial]
com = "COM5"
baud_rate = 9600